name: Deploy React + Vite App

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to 'main'

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run : |
            git config --global user.name "smart-coder-nilesh"
            git config --global user.email "mishranilesh@gmail.com"

            git checkout --orphan gh-pages

            git rm -rf .

            cp -r dist/* ./

            git add .

            git commit -m "Deploy to github pages"

            git push origin gh-pages --force
            git checkout master
